[[redirects]]
  from = "/challengeboard/*"
  to = "/challengeboard/index.html"
  status = 200

[[redirects]]
  from = "/mypage/*"
  to = "/mypage/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
